[buildPlans.IoZevkaCode]
family = "ioZevka Code"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

  [buildPlans.IoZevkaCode.variants]
  inherits = "ss14"

[buildPlans.IoZevkaCode.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IoZevkaCode.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IoZevkaCode.widths.Extended]
shape = 720
menu = 7
css = "expanded"

[buildPlans.IoZevkaCode.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IoZevkaCode.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IoZevkaCode.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IoZevkaCode.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IoZevkaQuasi]
family = "ioZevka Quasi"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
exportGlyphNames = true
noLigation = true

  [buildPlans.IoZevkaQuasi.variants]
  inherits = "ss14"

[buildPlans.IoZevkaQuasi.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IoZevkaQuasi.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IoZevkaQuasi.widths.Extended]
shape = 720
menu = 7
css = "expanded"

[buildPlans.IoZevkaQuasi.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IoZevkaQuasi.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IoZevkaQuasi.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IoZevkaQuasi.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IoZevkaSlabs]
family = "ioZevka Slabs"
spacing = "quasi-proportional"
serifs = "slab"
noCvSs = true
exportGlyphNames = true
noLigation = true

  [buildPlans.IoZevkaSlabs.variants]
  inherits = "ss14"

[buildPlans.IoZevkaSlabs.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IoZevkaSlabs.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IoZevkaSlabs.widths.Extended]
shape = 720
menu = 7
css = "expanded"

[buildPlans.IoZevkaSlabs.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IoZevkaSlabs.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IoZevkaSlabs.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IoZevkaSlabs.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IoZevkaTerm]
family = "ioZevka Term"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

  [buildPlans.IoZevkaTerm.variants]
  inherits = "ss14"

  [buildPlans.IoZevkaTerm.ligations]
  inherits = "dlig"

[buildPlans.IoZevkaTerm.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IoZevkaTerm.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IoZevkaTerm.widths.Extended]
shape = 720
menu = 7
css = "expanded"

[buildPlans.IoZevkaTerm.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IoZevkaTerm.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IoZevkaTerm.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IoZevkaTerm.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IoZevkaNerd]
family = "ioZevka Nerd"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

  [buildPlans.IoZevkaNerd.variants]
  inherits = "ss14"

  [buildPlans.IoZevkaNerd.ligations]
  inherits = "dlig"

[buildPlans.IoZevkaNerd.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IoZevkaNerd.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IoZevkaNerd.widths.Extended]
shape = 720
menu = 7
css = "expanded"

[buildPlans.IoZevkaNerd.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IoZevkaNerd.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IoZevkaNerd.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IoZevkaNerd.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IoZevkaMono]
family = "ioZevka Mono"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = true
noLigation = true

  [buildPlans.IoZevkaMono.variants]
  inherits = "ss14"

[buildPlans.IoZevkaMono.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IoZevkaMono.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IoZevkaMono.widths.Extended]
shape = 720
menu = 7
css = "expanded"

[buildPlans.IoZevkaMono.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IoZevkaMono.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IoZevkaMono.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IoZevkaMono.weights.Bold]
shape = 700
menu = 700
css = 700
